//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hitmans
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int detailId { get; set; }
        public string detailText { get; set; }
        public Nullable<int> hitmansId { get; set; }
    
        public virtual hitman hitman { get; set; }
    }
}
